#!/bin/bash
set -eou pipefail
set -o noclobber

DAY="$(date +'%d')"
TASK_FILE="src/bin/day$DAY.rs"

cat > "$TASK_FILE" << EOF
use utils::aoc_main;

fn part1(input: &str) -> u32 {
    unimplemented!();
}

fn part2(input: &str) -> u32 {
    unimplemented!();
}

fn main() {
    aoc_main!(part1);
}

#[cfg(test)]
mod tests {
    use super::*;

    static EXAMPLE_INPUT: &str = "";

    #[test]
    fn test_part1() {
        assert_eq!(part1(EXAMPLE_INPUT), 0);
    }

    //#[test]
    //fn test_part2() {
    //    assert_eq!(part2(EXAMPLE_INPUT), 0);
    //}
}
EOF
git add "$TASK_FILE"

if [[ -f ~/Downloads/input.txt ]]; then
    mv ~/Downloads/input.txt "input/$DAY.txt"
fi

_idea "$(dirname "$(realpath "$0")")" "$TASK_FILE"
