#!/bin/bash
set -eou pipefail
set -o noclobber

FILENAME="src/bin/day$(date +'%d').rs"
cat > "$FILENAME" << EOF
use scaffolding::aoc_main;

fn part1(input: &str) -> u32 {
    unimplemented!();
}

fn part2(input: &str) -> u32 {
    unimplemented!();
}

fn main() {
    aoc_main!(part1);
}

#[cfg(test)]
mod tests {
    use super::*;

    static EXAMPLE_INPUT: &str = "";

    #[test]
    fn test_part1() {
        assert_eq!(part1(EXAMPLE_INPUT), 0);
    }

    //#[test]
    //fn test_part2() {
    //    assert_eq!(part2(EXAMPLE_INPUT), 0);
    //}
}
EOF
git add "$FILENAME"
_idea "$(realpath "$0")" "$FILENAME"